### PR TITLE
fix: get_color should not throw error when name is not string

### PR DESCRIPTION
**Pull request by Miloas**

### CODE REVIEW

**Comment by fitrh** [comment]
AFAIK, this is a private function, not even exposed outside `utils.lua`, so I think it safe to assume that the function will always used correctly

**Comment by Miloas** [comment]
@fitrh yeah, you are right, but it will read the color from outside. And actually after I upgrade the plugin this morning, I met the error like `it's not a lua string, blabla` 😢

**Comment by fitrh** [comment]
@Miloas can you provide a minimum reproduction steps of your issue ? I use the latest version and works without any problem

**Comment by mvllow** [comment]
I am curious if you are you using any custom colours & what theme - we derive from the theme highlights which could provide something wonky

**Comment by Miloas** [comment]
> curious if you are you using any custom colours & what theme - we derive from the theme highlights which could provide something wonky
> 
> edit: maybe update and see if this issue persists as we reverted [4e69c2a](https://github.com/mvllow/modes.nvim/commit/4e69c2aa27a9a6166870a4383ea13eb4d864a1d7)

cool, it works! 

I use gruvbox theme, and it's CursorLineNr highlight is weird, so I set it to none.

**Pull request closed without merging**
