### PR TITLE
fix: add custom blend bg

### PR DESCRIPTION
**Pull request by adriankarlen**
I noticed that when using a transparent bg in neovim the blend function blends a bit weird as the Normal bg is set to "none". To fix this I wanted to add an optional color bg prop that can be used when blending.

#### Without custom bg
Screenshot 2024-06-05 103400

#### With custom bg
Screenshot 2024-06-05 103436

### CODE REVIEW

**Comment by zahimeen** [comment]
honestly, i am unsure why this plugin makes its own `blend` function when the `vim.api.nvim_set_hl` has a `blend` parameter. check `:help nvim_set_hl`

**Comment by mvllow** [comment]
Thank you, this seems to work great :)

@zahimeen I have not had luck using the builtin blend. We use it for our Rosé Pine theme but still implement the logic ourselves because it didn't appear to do anything. Happy to revisit in the future. I'm currently (slowly) rewriting modes to be simpler overall.

**Comment by zahimeen** [comment]
> Thank you, this seems to work great :)
> 
> @zahimeen I have not had luck using the builtin blend. We use it for our Rosé Pine theme but still implement the logic ourselves because it didn't appear to do anything. Happy to revisit in the future. I'm currently (slowly) rewriting modes to be simpler overall.

All good mate! Honestly, I have barely touched it myself and not sure about its functionality overall. The only case in which I have used it is from the Rosé Pine recipes for the status line. Anyways, good luck on the rewrite. There is a possibility I may have started my own rewrite of this plugin as well...

I love this plugin and your theme!

**Comment by mvllow** [comment]
My current rewrite progress is being tracked in #59

Happy to receive any feedback there :)

**Pull request merged**
